services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: lungcancer-qdrant
    ports:
      - "7000:6333"
      - "7001:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: